# ===============================
# Application
# ===============================
spring.application.name=lending

# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# Logging
# ===============================
logging.level.root=INFO
logging.level.com.lending.healthops_api=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# Database
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/healthOps?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# HikariCP (Professional Setup)
# ===============================
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HealthOpsHikariCP

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true